"""Core OAuth authentication workflow for the Gmail integration."""

import logging
from urllib.parse import urlparse, parse_qs
import httpx
from google_auth_oauthlib.flow import Flow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build

from app.integrations.gmail.config import CLIENT_SECRETS_PATH, REDIRECT_URI, SCOPES
from app.integrations.gmail.token_store import (
    load_credentials,
    save_credentials,
    save_metadata,
    load_metadata,
)

logger = logging.getLogger("openclaw-agent")


def is_connected() -> bool:
    """Check if Gmail credentials exist and are currently valid (refreshing if needed).

    Returns:
        True if credentials exist and are valid/refreshed, False otherwise.
    """
    creds = load_credentials()
    if not creds:
        return False
    if creds.expired:
        try:
            creds.refresh(Request())
            save_credentials(creds)
            return True
        except Exception as exc:
            logger.warning(f"Failed to refresh credentials during connection check: {exc}")
            return False
    return creds.valid


def get_authorization_url() -> str:
    """Generate the user authorization URL from client_secret.json.

    Returns:
        The OAuth2 consent screen authorization URL string.
    """
    if not CLIENT_SECRETS_PATH.exists():
        raise FileNotFoundError(f"Google OAuth client secrets file not found at: {CLIENT_SECRETS_PATH}")

    flow = Flow.from_client_secrets_file(
        str(CLIENT_SECRETS_PATH),
        scopes=SCOPES
    )
    flow.redirect_uri = REDIRECT_URI

    # Prompt consent to ensure a refresh token is returned
    auth_url, _ = flow.authorization_url(
        access_type="offline",
        prompt="consent"
    )

    # Cache the code_verifier generated by the flow for PKCE validation
    if hasattr(flow, "code_verifier") and flow.code_verifier:
        save_metadata({"code_verifier": flow.code_verifier})

    return auth_url


def complete_auth(callback_url: str) -> None:
    """Exchange authorization code from redirect URL for tokens, saving credentials and caching user email.

    Args:
        callback_url: The full redirect callback URL containing state and code query arguments.
    """
    parsed = urlparse(callback_url)
    params = parse_qs(parsed.query)
    code = params.get("code", [None])[0]

    # Fallback to direct code string if not a full callback URL
    if not code:
        if not parsed.netloc and not parsed.path.startswith("http"):
            code = callback_url
        else:
            raise ValueError("No authorization code found in redirect URL query parameters.")

    flow = Flow.from_client_secrets_file(
        str(CLIENT_SECRETS_PATH),
        scopes=SCOPES
    )
    flow.redirect_uri = REDIRECT_URI

    # Restore cached PKCE code_verifier
    meta = load_metadata()
    code_verifier = meta.get("code_verifier")
    if code_verifier:
        flow.code_verifier = code_verifier

    flow.fetch_token(code=code)

    credentials = flow.credentials
    save_credentials(credentials)

    # Fetch and cache authorized email address
    try:
        service = build("gmail", "v1", credentials=credentials)
        email = get_user_email(service)
        if email:
            save_metadata({"email": email})
            logger.info(f"Gmail integration authorized for email: {email}")
    except Exception as exc:
        logger.warning(f"Failed to fetch profile email address after OAuth exchange: {exc}")


def get_user_email(service) -> str | None:
    """Fetch profile email address from Gmail API service.

    Args:
        service: The authenticated googleapiclient Gmail service.

    Returns:
        The email address string, or None if query fails.
    """
    try:
        profile = service.users().getProfile(userId="me").execute()
        return profile.get("emailAddress")
    except Exception:
        return None


def revoke_token(token: str) -> bool:
    """Revoke user access token through Google's revocation endpoint.

    Args:
        token: The token string to revoke.

    Returns:
        True if the token was successfully revoked, False otherwise.
    """
    try:
        response = httpx.post(
            "https://oauth2.googleapis.com/revoke",
            params={"token": token},
            headers={"Content-Type": "application/x-www-form-urlencoded"},
            timeout=10.0
        )
        return response.status_code == 200
    except Exception as exc:
        logger.warning(f"Failed to revoke Google OAuth token: {exc}")
        return False
